### ISSUE TITLE
Question: Does this scale based on need ?

### ISSUE THREAD

**Issue by faizan002** [fortytwoservices/public-docs.fortytwo.io#44]
Hi,

are these elastic ? autoscaled runners ?

**Comment by mysteq** [comment]
The runners themself are not. That logic would need to exist outside, either by auto-scale rules on VMSS for Github, or some external logic that checks the Github job queue and scales the VMSS.
For Azure DevOps the integration itself in Azure DevOps manages the scaling based on your choices on the organization/project.
